// <auto-generated />
namespace MvcAlbum.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class edit01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit01));
        
        string IMigrationMetadata.Id
        {
            get { return "201409111017397_edit01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
